/// <auto-generated />
namespace MineJason.Tests.Client.Selectors;

using MineJason.Data.Selectors;

public class SelectorParsingTests
{
    [Fact]
    public void ParseWithName()
    {
        // Arrange
        const string sampleString = "@a[name=SomeName]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void ParseWithNameExcludes()
    {
        // Arrange
        const string sampleString = "@a[name=!SomeNameOne,name=!SomeNameTwo]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithTagExcludes()
    {
        // Arrange
        const string sampleString = "@a[tag=!SomeNameOne,tag=!SomeNameTwo]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithTagIncludesAndExcludes()
    {
        // Arrange
        const string sampleString = "@a[tag=RealTagZero,tag=RealTagOne,tag=!SomeNameOne,tag=!SomeNameTwo]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithPositionAndDistance()
    {
        // Arrange
        const string sampleString = "@a[x=250,y=110,z=2491,distance=..20]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithScores()
    {
        // Arrange
        const string sampleString = "@a[x=250,y=110,z=2491,scores={objective0=100,objective1=90..250,objective2=..77,objective3=55..}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithGameModeExcludes()
    {
        // Arrange
        const string sampleString = "@a[gamemode=!adventure,gamemode=!creative]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithGameModeRequirement()
    {
        // Arrange
        const string sampleString = "@a[gamemode=adventure]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithLevels()
    {
        // Arrange
        const string sampleString = "@a[level=56..100]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithNoArguments()
    {
        // Arrange
        const string sampleString = "@a";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithXRotationRange()
    {
        // Arrange
        const string sampleString = "@a[x_rotation=-180..180]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithYRotationRange()
    {
        // Arrange
        const string sampleString = "@a[y_rotation=-180..180]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithType()
    {
        // Arrange
        const string sampleString = "@a[type=minecraft:player]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithNbtCondition()
    {
        // Arrange
        const string sampleString = "@a[nbt={Condition:1b}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithOneAdvancementCondition()
    {
        // Arrange
        const string sampleString = "@a[advancements={minecraft:adventure/kill_all_mobs={witch=true}}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithTwoAdvancementConditions()
    {
        // Arrange
        const string sampleString = "@a[advancements={minecraft:adventure/kill_all_mobs={witch=true},minecraft:story/form_obsidian=false}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithOneAdvancementCondition_MultipleCriterion()
    {
        // Arrange
        const string sampleString = "@a[advancements={minecraft:adventure/kill_all_mobs={witch=true,zombie=false,skeleton=true}}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithMultipleNbtConditions()
    {
        // Arrange
        const string sampleString = "@a[nbt={Condition:1b},nbt=!{NonCondition:2b}]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithSinglePredicate_DoMatch()
    {
        // Arrange
        const string sampleString = "@a[predicate=custom:predicate]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithSinglePredicate_NoMatch()
    {
        // Arrange
        const string sampleString = "@a[predicate=!custom:mismatch]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_ParseWithMultiplePredicates()
    {
        // Arrange
        const string sampleString = "@a[predicate=!custom:mismatch,predicate=custom:matches_now]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
    [Fact]
    public void Parser_NearestEntity()
    {
        // Arrange
        const string sampleString = "@n[predicate=minecraft:predicate]";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }
}
