version = 1

[[annotations]]
path = global.json
SPDX-FileCopyrightText = (C) WithLithum & contributors 2023-2026
SPDX-License-Identifier = Apache-2.0

[[annotations]]
path = **/*.Designer.cs
SPDX-FileCopyrightText = (C) WithLithum & contributors 2023-2026
SPDX-License-Identifier = Apache-2.0

[[annotations]]
path = **/*.resx
SPDX-FileCopyrightText = (C) WithLithum & contributors 2023-2026
SPDX-License-Identifier = Apache-2.0

# Client module has a different licence

[[annotations]]
path = src/MineJason/**/*.Designer.cs
SPDX-FileCopyrightText = (C) WithLithum & contributors 2023-2026
SPDX-License-Identifier = LGPL-3.0-or-later

[[annotations]]
path = src/MineJason/**/*.resx
SPDX-FileCopyrightText = (C) WithLithum & contributors 2023-2026
SPDX-License-Identifier = LGPL-3.0-or-later