//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineJason.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineJason.Properties.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t know how to decode value of type &apos;{0}&apos;.
        /// </summary>
        internal static string ResultDoesNotKnowTypeDecode {
            get {
                return ResourceManager.GetString("ResultDoesNotKnowTypeDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t know how to encode value of type &apos;{0}&apos;.
        /// </summary>
        internal static string ResultDoesNotKnowTypeEncode {
            get {
                return ResourceManager.GetString("ResultDoesNotKnowTypeEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed resource location &apos;{0}&apos;.
        /// </summary>
        internal static string ResultMalformedResourceLocation {
            get {
                return ResourceManager.GetString("ResultMalformedResourceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to multiple dialogs isn&apos;t allowed here.
        /// </summary>
        internal static string ResultMultiDialogSourceDisallowed {
            get {
                return ResourceManager.GetString("ResultMultiDialogSourceDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a dialog source.
        /// </summary>
        internal static string ResultNotDialogSource {
            get {
                return ResourceManager.GetString("ResultNotDialogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types outside of &apos;minecraft&apos; namespace are not supported.
        /// </summary>
        internal static string ResultNotMinecraftSpace {
            get {
                return ResourceManager.GetString("ResultNotMinecraftSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not supported.
        /// </summary>
        internal static string ResultUnsupportedValue {
            get {
                return ResourceManager.GetString("ResultUnsupportedValue", resourceCulture);
            }
        }
    }
}
