$definitionFile = "selectorTestLines.json"
$outputFile = "SelectorParsingTests.cs"

$map = Get-Content -Path $definitionFile | ConvertFrom-Json -AsHashtable
$stream = [System.IO.File]::Create($outputFile);
$writer = New-Object System.IO.StreamWriter -ArgumentList @($stream)

$writer.WriteLine("/// <auto-generated />")

$writer.WriteLine("namespace MineJason.Tests;

using MineJason.Data;
using MineJason.Data.Selectors;
using MineJason.Exceptions;

public class SelectorParsingTests
{");

foreach ($key in $map.Keys) {
    $writer.WriteLine("    [Fact]
    public void ${key}()
    {
        // Arrange
        const string sampleString = ""$($map[$key])"";

        // Act
        var parseResult = EntitySelectorStringFormatter.ParseSelector(sampleString).ToString();

        // Assert
        Assert.Equal(sampleString, parseResult);
    }")
}

$writer.WriteLine("}")
$writer.Dispose()