# SPDX-FileCopyrightText: (C) WithLithum & contributors 2023-2026
# SPDX-License-Identifier: Apache-2.0

name: Dependency scanning

on:
  push:
    branches: [ main ]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      name: Checkout

    - uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
      with:
        api-key: ${{secrets.FOSSA_API_KEY}}
        working-directory: ${{ github.workspace }}